services:
  - type: web
    name: uptime-kuma
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: false
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
